test:
	g++ -DARDUINO -I./mocks -o unit-test-1 unit-test-1.cpp \
	../WARS-Birdhouse/OutboundPacket.cpp \
	../WARS-Birdhouse/OutboundPacketManager.cpp \
	../WARS-Birdhouse/RoutingTable.cpp \
	../WARS-Birdhouse/MessageProcessor.cpp
	./unit-test-1 